version: '2'
services:
{%- if cookiecutter.use_mysql == 'y' %}
  mysql:
    image: mysql:{{ cookiecutter.mysql_version }}
    restart: always
    expose:
      - "{{ cookiecutter.mysql_port }}"
    environment:
      MYSQL_DATABASE: {{ cookiecutter.mysql_database }}
      MYSQL_USER: {{ cookiecutter.mysql_user }}
      MYSQL_PASSWORD: {{ cookiecutter.mysql_password }}
      MYSQL_ROOT_PASSWORD: {{ cookiecutter.mysql_root_password }}
    volumes:
      - "./mysql/.data/db:/var/lib/mysql"
{%- endif %}
{%- if cookiecutter.use_postgres == 'y' %}
  postgres:
    image: postgres:{{ cookiecutter.postgres_version }}
    restart: always
    expose:
      - "{{ cookiecutter.postgres_port }}"
    environment:
      POSTGRESQL_DATABASE: {{ cookiecutter.postgres_database }}
      POSTGRESQL_USER: {{ cookiecutter.postgres_user }}
      POSTGRESQL_PASSWORD: {{ cookiecutter.postgres_password }}
      POSTGRESQL_ROOT_PASSWORD: {{ cookiecutter.postgres_root_password }}
    volumes:
      - "./postgresql/.data/db:/var/lib/postgresql"
{%- endif %}
  web:
    restart: always
    build: .
    working_dir: /opt/{{ cookiecutter.app_name }}
    command: python3 manage.py start
    depends_on:
      - mysql
    expose:
      - "5000"
    volumes:
      - ./{{ cookiecutter.app_name }}:/opt/{{ cookiecutter.app_name }}
    environment:
      APP_ENV: Docker
{%- if cookiecutter.use_mysql == 'y' %}
      MYSQL_DATABASE: {{ cookiecutter.mysql_database }}
      MYSQL_USER: {{ cookiecutter.mysql_user }}
      MYSQL_PASSWORD: {{ cookiecutter.mysql_password }}
      MYSQL_ROOT_PASSWORD: {{ cookiecutter.mysql_root_password }}
      MYSQL_HOST: {{ cookiecutter.mysql_host }}
      MYSQL_PORT: {{ cookiecutter.mysql_port }}
{%- endif %}
    links:
{%- if cookiecutter.use_mysql == 'y' %}
      - mysql:{{ cookiecutter.mysql_host }}
{%- endif %}
{%- if cookiecutter.use_postgres == 'y' %}
      - postgres:{{ cookiecutter.postgres_host }}
{%- endif %}
